name: Android Build

on:
  push:
    branches: [ jason ]

  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v1

      - name: Set UP JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Ready Build...
        run: cd android
        
      - name: Run Tests
        run: ./gradlew test
      
      - name: Build Project
        run: ./gradlew assemble
