name: Deploy
 
on:
 workflow_dispatch:

jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
    - name: job1 step1
      run: echo job1 step1

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: job2 step1
      run: echo job2 step1
    
  job3:
    if: always()
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
    - name: job3 step1
      run: echo job3 step1
  

