name: Deploy
 
on:
 
  push:
 
    branches: main
 
jobs:
 
  build:
 
    runs-on: ubuntu-latest
 
 
 
 
    steps:
 
    - uses: actions/checkout@v2
 
    - name: Set up JDK 1.8
 
      uses: actions/setup-java@v1
 
      with:
 
        java-version: 1.8
 
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
 
        settings-path: $ # location for the settings.xml file
 
     
 
#     - name: Build with Gradle
#       run: ./gradlew build
 
       
#Debug용 Key Hash
#    - name: get Key Hash
 
#      run: keytool -exportcert -alias androiddebugkey -keystore %HOMEPATH%\.android\debug.keystore | openssl sha1 -binary | openssl base64
 
     
 
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
 
       
 
    - name: Build APK
      run: bash ./gradlew assembleRelease --stacktrace
 
       
 
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app_$
        path: app/build/outputs/release/app-release.apk
